name: portal-test
version: 1
summary: xdg-desktop-portal test application
description: |
  This test application exercises the features of xdg-desktop-portal

grade: devel
confinement: strict

slots:
  portal-test-dbus:
    interface: dbus
    bus: session
    name: org.gnome.PortalTest

apps:
  portal-test:
    command: desktop-launch $SNAP/bin/portal-test
    environment:
      GTK_USE_PORTAL: 1
    plugs:
      - desktop
      - gsettings
      - wayland
      - x11
    slots:
      - portal-test-dbus

parts:
  portal-test:
    after:
      - desktop-gtk3
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/

    build-packages:
      - gcc
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
